<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>final_project_biol</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Final_Project_BIOL_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_Project_BIOL_files/libs/quarto-html/quarto.js"></script>
<script src="Final_Project_BIOL_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_Project_BIOL_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_Project_BIOL_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_Project_BIOL_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_Project_BIOL_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_Project_BIOL_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_Project_BIOL_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_Project_BIOL_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<table class="caption-top table">
<tbody>
<tr class="odd">
<td>title: “Final_Project_BIOL” author: “Kevin Fantinatti” format: pdf:</td>
</tr>
</tbody>
</table>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In the pursuit of sustainable strawberry cultivation, the practice of mulching plays a pivotal role in determining both yield and plant health. Traditional methods often involve the use of black plastic mulch, which effectively suppresses weeds but restricts the natural growth of strawberry plants, preventing them from sending out runners.</p>
<p>As a result, many growers replant after a few years to maintain optimal production levels. However, some growers opt to extend the life of their existing plantings under plastic for an additional season, driven by the significant costs associated with establishing new crops. This raises an important question: would transitioning from plastic mulch to straw mulch — often referred to as “renovation” — benefit these growers by enhancing yield?</p>
<p>This study aims to explore this question by examining the impact of such a transition on three different varieties of strawberries, providing valuable insights for growers in the Northeast looking to optimize their practices and ensure the sustainability of their operations.</p>
<p>The hypothesis is that strawberry varieties under straw mulch treatment will produce better results than plastic treatment because the plants can root runners into the soil without being obstructed by black plastic. We believe this natural rooting process will enhance the overall growth and yield of the plants.</p>
</section>
<section id="material-and-methods" class="level1">
<h1>Material and Methods</h1>
<section id="treatments" class="level2">
<h2 class="anchored" data-anchor-id="treatments">Treatments</h2>
<p>This study evaluated three varieties of crops, all of which were scheduled for harvest in June. The varieties included Wendy (W), which was noted for its early production; Allstar (A), which had a mid-range harvest time; and Valley Sunset (VS), the latest of the three varieties.</p>
</section>
<section id="mulch-treatments" class="level2">
<h2 class="anchored" data-anchor-id="mulch-treatments">Mulch Treatments</h2>
<p>Two distinct mulch treatments were applied to the plots. The “Plastic” treatment involved plots that had previously been covered with plastic mulch, which was left in place for the duration of the study. The “Straw” treatment, on the other hand, consisted of plots that had originally been covered with plastic mulch, but this plastic was removed and replaced with straw mulch.</p>
</section>
<section id="data-collection-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-collection-and-analysis">Data Collection and Analysis</h2>
<p>Data was collected on the harvest date for each plot to track the timing of production across the different varieties. Lastly, the row layout of the experimental design was considered a potential blocking variable, although the particulars of this design were not fully defined, as it was overlaid on a previous experiment. Statistical models and data cleaning were performed using R software.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The first results of the study are presented in Table 1, which summarizes the mean yield of strawberries across different varieties and mulch treatments. The mean yields observed for each treatment are as follows:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Crops Yields by Variety and Treatments.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variety</th>
<th style="text-align: left;">Treatment</th>
<th style="text-align: right;">Mean_Yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Plastic</td>
<td style="text-align: right;">89.95714</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Straw</td>
<td style="text-align: right;">195.71961</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VS</td>
<td style="text-align: left;">Plastic</td>
<td style="text-align: right;">58.92000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VS</td>
<td style="text-align: left;">Straw</td>
<td style="text-align: right;">185.54884</td>
</tr>
<tr class="odd">
<td style="text-align: left;">W</td>
<td style="text-align: left;">Plastic</td>
<td style="text-align: right;">59.15161</td>
</tr>
<tr class="even">
<td style="text-align: left;">W</td>
<td style="text-align: left;">Straw</td>
<td style="text-align: right;">310.21556</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>For Variety Allstar(A), the yields were 89.95714 kg/ha with Plastic and 195.71961 kg/ha with Straw mulch.</li>
<li>For Variety Valley Sunset(VS), the yields were 58.92000 kg/ha with Plastic and 185.54884 kg/ha with Straw mulch.</li>
<li>For Variety Wendy(w), the yields were 59.15161 kg/ha with Plastic and 310.21556 kg/ha with Straw mulch.</li>
</ul>
<p>These results indicate that the type of mulch treatment had a significant impact on the overall yield of strawberries, as demonstrated in Figures 1 and 2.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_BIOL_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_BIOL_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Furthermore, a two-way ANOVA was conducted to evaluate the effects of crop variety and mulch treatment on yield (Table 2). The results showed that mulch treatment had a significant effect on yield (F = 20.36, p &lt; 0.001), with Plastic mulch outperforming Straw mulch. Crop variety did not significantly affect yield (F = 1.35, p = 0.261), and there was no significant interaction between variety and mulch treatment (F = 1.63, p = 0.198). These results suggest that mulch treatment is a key factor influencing yield, regardless of the crop variety.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. ANOVA two-way</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">DF</th>
<th style="text-align: right;">F_Statistic</th>
<th style="text-align: right;">P_Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.353437</td>
<td style="text-align: right;">0.2605227</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.360218</td>
<td style="text-align: right;">0.0000105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Variety:Treatment</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.629185</td>
<td style="text-align: right;">0.1984784</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">217</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_BIOL_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As shown in Figure 4, no significant differences were observed in yield among the various strawberry varieties when subjected to the same mulch treatment. This suggests that the choice of mulch plays a critical role in yield performance, while the variety itself does not significantly affect the yield under the tested conditions in order to test if strawberry varieties developed different when under different treatment a ANOVA statistical model were made.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_BIOL_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3. ANOVA two-way for Variety-Yield</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">DF</th>
<th style="text-align: right;">F_Statistic</th>
<th style="text-align: right;">P_Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Variety</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.237461</td>
<td style="text-align: right;">0.2921311</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The ANOVA statistical analysis presented on table 3, confirmed that there are no difference between varieties yield production, this represents that all varieties have the similar performances when are under the same conditions. The overall production yield for Allstar (A), Valley Sunset (VS) and Wendy (W) suggests that are no differences of marketable yield among the varieties.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The analysis conducted in this study identified that the type of mulch treatment (Plastic or Straw) significantly affects the strawberry crop yield. The Allstar (A), Valley Sunset (VS), and Wendy (W) performed, respectively, 117.57%, 214.92%, and 424.44% better under straw mulch treatment than using plastics. This finding emphasizes the critical role that straw mulch choice plays in strawberry cultivation.</p>
<p>Additionally, the investigation revealed that there were no significant differences in yield among the three varieties of strawberries assessed. The Wendy (W) variety performed with a higher yield than others under straw mulch. However, the ANOVA statistical analysis showed that there were no significant effects of interaction between mulch treatment and variety. This means that the influence of mulch treatment on yield remains consistent across all varieties, indicating that there is no specific combination of variety and mulch treatment that provides a unique advantage in terms of yield performance.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study aimed to assess the impact of transitioning from plastic to straw mulch on the yield of three strawberry varieties, namely Wendy, Allstar, and Valley Sunset. Our findings confirmed the hypothesis that strawberry varieties would perform better under straw mulch treatment. This provide valuable insights for strawberry growers in the Northeast who are considering innovative approaches to enhance production sustainability.</p>
<p>The results indicate that removing plastic and replacing it with straw mulch can have a positive effect on yield. This is likely due to the enhanced root development afforded by the absence of the plastic barrier, allowing the plants to send out runners and establish a more robust root system. Our hypothesis that Straw plots would yield better than Plastic plots was supported by the data collected and statistical analysis, demonstrating the advantages of this technique.</p>
<p>In conclusion, the transition to straw mulch represents a promising strategy for growers who wish to maximize the longevity and productivity of their strawberry crops. By adopting this practice, producers can capitalize on enhanced yields and healthier plants, ultimately leading to more sustainable strawberry cultivation in the region. As farmers continue to seek methods that balance economic viability with environmental stewardship, this study underscores the potential benefits of exploring alternative mulching practices. Further research is recommended to explore the long-term effects of straw mulch on soil health and additional crop varieties, ensuring that strawberry growers can make informed decisions for their operations.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>